# PostgreSQL credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=         # base64 of "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM=     # base64 of "password"
  POSTGRES_DB: Y2xpbmljYWxfdHJpYWxz   # base64 of "clinical_trials"
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvY2xpbmljYWxfdHJpYWxz